# This file was generated by GoReleaser. DO NOT EDIT.
cask "trau" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "05463e22a0d0a16598961285c5c8017c9f53bf7c9c1d4ff75c0ac236b94eb1a7"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "543c97dba9bee7163486e4a8ba859a16d1792b05961f051f920ef6579ddd5030"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "704f69e3b4cfe034b83b6c5e245cbebada2f3fa9b27df17553090b8d56c20674"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c06f708cba36c5b0aad40e429a0f91cb384b3c095bde61c61795015d3a11078c"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trau"
  desc "Autonomous, ticket-driven development loop"
  homepage "https://github.com/RomkaLTU/trau"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trau"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trau"]
    end
  end

  # No zap stanza required

end
