# This file was generated by GoReleaser. DO NOT EDIT.
cask "trau" do
  version "0.18.1"

  on_macos do
    on_intel do
      sha256 "f3f325bb8e9665eff34cd4b747344653bd57c3e6a3c60b9d94417ea594c6d193"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e3a7e8d33193e964d1ba31501abf7c0b05447cfb45f3bba1bf25f0639d37a6b"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "300413bfc7581ffeaf8debb9a901763588a89d699a21d6c4845e6a3dabfee987"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b42b590e64bd3d472dca08ee3953d676dae3cb893455eec6b4479b8fc954d1b2"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trau"
  desc "Autonomous, ticket-driven development loop"
  homepage "https://trau.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trau"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trau"]
    end
  end

  # No zap stanza required

end
