# This file was generated by GoReleaser. DO NOT EDIT.
cask "trau" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ac648dc58b5dd3a89982ba9d7100e52690902cb5022f22c1e291e3695cc94104"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bab1e34509dc09a441e5a1840dd51505e4987f64bc1234c66b9fdae9bd6c7a8"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0b4be11fc9e76902630e608b59c29d4070f8b89fc5a9eb27a4e9a2b24578a2f8"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "26266afae286e72784029b710ca3d3d7f1589df667023eac244ea3b61bafa226"
      url "https://github.com/RomkaLTU/trau/releases/download/v#{version}/trau_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trau"
  desc "Autonomous, ticket-driven development loop"
  homepage "https://trau.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trau"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trau"]
    end
  end

  # No zap stanza required

end
